"""Regression guard for the refactor branch's supported import surface."""

from __future__ import annotations

import beamz
import beamz.analysis as analysis
import beamz.design as design
import beamz.devices.modes as modes
import beamz.devices.monitors as monitors
import beamz.devices.sources as sources
import beamz.optimization as optimization
import beamz.simulation as simulation

EXPECTED_EXPORTS = {
    "beamz": (
        "LIGHT_SPEED",
        "VAC_PERMITTIVITY",
        "VAC_PERMEABILITY",
        "EPS_0",
        "MU_0",
        "um",
        "nm",
        "µm",
        "μm",
        "Material",
        "design",
        "optimization",
        "Design",
        "Box",
        "Rectangle",
        "Circle",
        "Ring",
        "CircularBend",
        "Polygon",
        "Taper",
        "Sphere",
        "ModeSource",
        "ModeData",
        "GaussianSource",
        "GaussianBeamSource",
        "CustomSource",
        "FieldMonitor",
        "FieldRecorder",
        "FluxMonitor",
        "ModeMonitor",
        "Port",
        "ramped_cosine",
        "Simulation",
        "GridSpec",
        "MeshOverride",
        "Grid",
        "RectilinearGrid",
        "AxisGridQuality",
        "GridQualityReport",
        "GaussianPulse",
        "SampledSignal",
        "ModeSpec",
        "inf",
        "MonitorResults",
        "SimulationResults",
        "SimulationRun",
        "SimulationState",
        "AutoTermination",
        "RunTermination",
        "PML",
        "PEC",
        "Absorber",
        "display_status",
        "create_plain_progress",
        "get_si_scale_and_label",
        "calc_optimal_fdtd_params",
        "dxdt",
        "SParameterResult",
    ),
    "beamz.analysis": (
        "get_plotting_backend",
        "get_pyplot",
        "plotting_backend",
        "set_plotting_backend",
        "ModeMonitorData",
        "SParameterResult",
        "SourceNormalization",
        "mode_data",
        "mode_data_to_dataframe",
        "monitor_dft_component",
        "monitor_flux",
        "monitor_to_xarray",
        "s_parameters",
        "save_field_video",
        "source_normalization",
        "to_xarray",
    ),
    "beamz.design": (
        "Material",
        "Design",
        "MaterialGrid",
        "build_material_grid",
        "Box",
        "Rectangle",
        "Circle",
        "Ring",
        "CircularBend",
        "Polygon",
        "Taper",
        "GridSpec",
        "MeshOverride",
        "Grid",
        "RectilinearGrid",
        "AxisGridQuality",
        "GridQualityReport",
        "ImportedComponent",
        "import_component",
        "import_gds",
        "export_gds",
        "GDSFactorySettings",
        "ComponentSimulationResults",
        "PortMetadata",
        "PreparedComponent",
        "prepare_gdsfactory",
    ),
    "beamz.devices.monitors": (
        "FieldMonitor",
        "FieldRecorder",
        "FluxMonitor",
        "ModeMonitor",
    ),
    "beamz.devices.modes": (
        "ModeData",
        "ModeSpec",
        "Result",
        "solve_grid",
    ),
    "beamz.devices.sources": (
        "ModeSource",
        "ModeSpec",
        "ModeData",
        "GaussianPulse",
        "SampledSignal",
        "GaussianSource",
        "GaussianBeamSource",
        "CustomSource",
    ),
    "beamz.optimization": (
        "topology",
        "adjoint_memmap",
        "smoothed_heaviside",
        "subpixel_smoothed_projection",
        "density_to_shapely_geometry",
        "shapely_geometry_to_polygons",
        "density_to_polygons",
        "TopologySpec",
        "TopologyState",
    ),
    "beamz.simulation": (
        "Simulation",
        "Port",
        "MonitorResults",
        "SimulationResults",
        "SimulationRun",
        "SimulationState",
        "AutoTermination",
        "RunTermination",
        "GridSpec",
        "GaussianPulse",
        "ModeSpec",
        "inf",
        "PML",
        "PEC",
        "Absorber",
    ),
}


def test_supported_module_exports_are_frozen():
    modules = (
        beamz,
        analysis,
        design,
        modes,
        monitors,
        sources,
        optimization,
        simulation,
    )
    for module in modules:
        expected = EXPECTED_EXPORTS[module.__name__]
        assert tuple(module.__all__) == expected
        assert all(hasattr(module, name) for name in expected)
