// Generated by scripts/generate_cuda_abi.py. Do not edit by hand.
#ifndef BEAMZ_CUDA_ABI_LAYOUT_H_
#define BEAMZ_CUDA_ABI_LAYOUT_H_

#include <cstddef>
#include <cstdint>

namespace beamz::cuda::abi {

inline constexpr int32_t kAbiVersion = 15;
inline constexpr char kComponentVersion[] = "0.15.0";
inline constexpr char kStreamedTarget[] = "beamz_cuda_streamed";
inline constexpr char kProgramTarget[] = "beamz_cuda_program";
inline constexpr char kHopperTarget[] = "beamz_cuda_hopper";

inline constexpr int32_t kBeamzGraphCache = 1 << 7;
inline constexpr int32_t kBeamzBf16Psi = 1 << 12;
inline constexpr int32_t kBeamzDefaultFlags = kBeamzGraphCache;

inline constexpr int32_t kNativeScheduleCpml = 1 << 0;
inline constexpr int32_t kNativeScheduleTemporal = 1 << 1;
inline constexpr int32_t kNativeScheduleUniformCpml = 1 << 2;
inline constexpr int32_t kNativeSchedulePackedMaterial = 1 << 3;
inline constexpr int32_t kNativeScheduleCombinedCpmlCore = 1 << 4;
inline constexpr int32_t kNativeScheduleSources = 1 << 5;
inline constexpr int32_t kNativeScheduleMonitors = 1 << 6;
inline constexpr int32_t kNativeScheduleGraphCache = 1 << 7;

inline constexpr int32_t kProgramLayoutYeeInPlace = 0;
inline constexpr int32_t kProgramLayoutYeeTemporal = 1;
inline constexpr int32_t kProgramLayoutCpmlInPlace = 2;
inline constexpr int32_t kProgramLayoutSourceInPlace = 3;
inline constexpr int32_t kProgramLayoutSourceTemporalCpml = 4;
inline constexpr int32_t kProgramLayoutMonitorInPlace = 5;
inline constexpr int32_t kProgramLayoutMonitorTemporalCpml = 6;

inline constexpr size_t kFieldCount = 6;
inline constexpr size_t kCpmlTermCount = 6;
inline constexpr size_t kSourceGroupCount = 9;
inline constexpr size_t kSourceGroupBufferCount = 3;
inline constexpr size_t kSourceGroupCoefficientsInput = 0;
inline constexpr size_t kSourceGroupWaveformsInput = 1;
inline constexpr size_t kSourceGroupStartsInput = 2;
inline constexpr size_t kMonitorInputCount = 15;
inline constexpr size_t kMonitorIndicesInput = 0;
inline constexpr size_t kMonitorWeightsInput = 1;
inline constexpr size_t kMonitorFrequenciesInput = 2;
inline constexpr size_t kMonitorComponentMasksInput = 3;
inline constexpr size_t kMonitorCountsInput = 4;
inline constexpr size_t kMonitorCodesInput = 5;
inline constexpr size_t kMonitorWindowsInput = 6;
inline constexpr size_t kMonitorDftReInput = 7;
inline constexpr size_t kMonitorDftImInput = 8;
inline constexpr size_t kMonitorDftWeightInput = 9;
inline constexpr size_t kMonitorPhaseSinInput = 10;
inline constexpr size_t kMonitorPhaseCosInput = 11;
inline constexpr size_t kMonitorPhaseWindowInput = 12;
inline constexpr size_t kMonitorTimeInput = 13;
inline constexpr size_t kMonitorCurrentStepInput = 14;
inline constexpr size_t kYeeGraphInputCount = 24;
inline constexpr size_t kYeeGraphOutputCount = 6;
inline constexpr size_t kCpmlGraphInputCount = 74;
inline constexpr size_t kCpmlGraphOutputCount = 18;
inline constexpr size_t kCpmlPhaseInputCount = 31;
inline constexpr size_t kCpmlEInputOffset = 37;
inline constexpr size_t kCpmlHMetricOffset = 68;
inline constexpr size_t kCpmlEMetricOffset = 71;
inline constexpr size_t kCpmlHPsiInputOffset = 31;
inline constexpr size_t kCpmlEPsiInputOffset = 62;
inline constexpr size_t kTemporalHPsiOutputOffset = 12;
inline constexpr size_t kTemporalEPsiOutputOffset = 18;
inline constexpr size_t kTemporalHPsiWorkspaceOffset = 24;
inline constexpr size_t kTemporalEPsiWorkspaceOffset = 30;
inline constexpr size_t kTemporalFieldWorkspaceInput = 74;
inline constexpr size_t kTemporalPsiWorkspaceInput = 80;

}  // namespace beamz::cuda::abi

#endif
