#!/usr/bin/env python3
"""Generate the Python and C++ CUDA FFI contract from one JSON schema."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "cuda" / "abi_layout.json"
PYTHON_OUTPUT = ROOT / "beamz" / "simulation" / "_cuda_abi.py"
CPP_OUTPUT = ROOT / "cuda" / "src" / "abi_layout.h"


def _pascal_case(value: str) -> str:
    return "".join(part.capitalize() for part in value.split("_"))


def _render_python(schema: dict) -> str:
    targets = schema["targets"]
    exported = [
        "CUDA_ABI_VERSION",
        "CUDA_COMPONENT_VERSION",
        *(f"CUDA_{name.upper()}_TARGET" for name in targets),
        "CUDA_STREAMED_TARGETS",
        *(f"CUDA_{name.upper()}" for name in schema["flags"]),
        "CUDA_DEFAULT_FLAGS",
        *(f"NATIVE_SCHEDULE_{name.upper()}" for name in schema["schedule_flags"]),
        *(f"PROGRAM_LAYOUT_{name.upper()}" for name in schema["program_layouts"]),
        *(name.upper() for name in schema["layout"]),
    ]
    lines = [
        '"""Generated CUDA FFI contract. Do not edit by hand."""',
        "",
        "__all__ = [",
        *(f"    {json.dumps(name)}," for name in exported),
        "]",
        "",
        f"CUDA_ABI_VERSION = {schema['abi_version']}",
        f"CUDA_COMPONENT_VERSION = {json.dumps(schema['component_version'])}",
    ]
    for name, target in targets.items():
        lines.append(f"CUDA_{name.upper()}_TARGET = {json.dumps(target)}")
    lines.extend(["", "CUDA_STREAMED_TARGETS = frozenset(", "    ("])
    lines.extend(
        f"        CUDA_{name.upper()}_TARGET," for name in schema["streamed_targets"]
    )
    lines.extend(["    )", ")", ""])
    for name, bit in schema["flags"].items():
        lines.append(f"CUDA_{name.upper()} = 1 << {bit}")
    default_flags = " | ".join(
        f"CUDA_{name.upper()}" for name in schema["default_flags"]
    )
    lines.extend([f"CUDA_DEFAULT_FLAGS = {default_flags or 0}", ""])
    for name, bit in schema["schedule_flags"].items():
        lines.append(f"NATIVE_SCHEDULE_{name.upper()} = 1 << {bit}")
    lines.append("")
    for name, value in schema["program_layouts"].items():
        lines.append(f"PROGRAM_LAYOUT_{name.upper()} = {value}")
    lines.append("")
    for name, value in schema["layout"].items():
        lines.append(f"{name.upper()} = {value}")
    lines.append("")
    return "\n".join(lines)


def _render_cpp(schema: dict) -> str:
    lines = [
        "// Generated by scripts/generate_cuda_abi.py. Do not edit by hand.",
        "#ifndef BEAMZ_CUDA_ABI_LAYOUT_H_",
        "#define BEAMZ_CUDA_ABI_LAYOUT_H_",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace beamz::cuda::abi {",
        "",
        f"inline constexpr int32_t kAbiVersion = {schema['abi_version']};",
        (
            f"inline constexpr char kComponentVersion[] = "
            f'"{schema["component_version"]}";'
        ),
    ]
    for name, target in schema["targets"].items():
        lines.append(
            f'inline constexpr char k{_pascal_case(name)}Target[] = "{target}";'
        )
    lines.append("")
    for name, bit in schema["flags"].items():
        lines.append(
            f"inline constexpr int32_t kBeamz{_pascal_case(name)} = 1 << {bit};"
        )
    default_flags = " | ".join(
        f"kBeamz{_pascal_case(name)}" for name in schema["default_flags"]
    )
    lines.extend(
        [f"inline constexpr int32_t kBeamzDefaultFlags = {default_flags or 0};", ""]
    )
    for name, bit in schema["schedule_flags"].items():
        lines.append(
            f"inline constexpr int32_t kNativeSchedule{_pascal_case(name)} = 1 << {bit};"
        )
    lines.append("")
    for name, value in schema["program_layouts"].items():
        lines.append(
            f"inline constexpr int32_t kProgramLayout{_pascal_case(name)} = {value};"
        )
    lines.append("")
    for name, value in schema["layout"].items():
        lines.append(f"inline constexpr size_t k{_pascal_case(name)} = {value};")
    lines.extend(["", "}  // namespace beamz::cuda::abi", "", "#endif", ""])
    return "\n".join(lines)


def _write_or_check(path: Path, expected: str, *, check: bool) -> bool:
    if check:
        return path.exists() and path.read_text() == expected
    path.write_text(expected)
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail if generated files are stale"
    )
    args = parser.parse_args()
    schema = json.loads(SCHEMA.read_text())
    outputs = {
        PYTHON_OUTPUT: _render_python(schema),
        CPP_OUTPUT: _render_cpp(schema),
    }
    stale = [
        path
        for path, content in outputs.items()
        if not _write_or_check(path, content, check=args.check)
    ]
    if stale:
        for path in stale:
            print(f"stale generated CUDA ABI file: {path.relative_to(ROOT)}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
