"""Generated CUDA FFI contract. Do not edit by hand."""

__all__ = [
    "CUDA_ABI_VERSION",
    "CUDA_COMPONENT_VERSION",
    "CUDA_STREAMED_TARGET",
    "CUDA_PROGRAM_TARGET",
    "CUDA_HOPPER_TARGET",
    "CUDA_STREAMED_TARGETS",
    "CUDA_GRAPH_CACHE",
    "CUDA_BF16_PSI",
    "CUDA_DEFAULT_FLAGS",
    "NATIVE_SCHEDULE_CPML",
    "NATIVE_SCHEDULE_TEMPORAL",
    "NATIVE_SCHEDULE_UNIFORM_CPML",
    "NATIVE_SCHEDULE_PACKED_MATERIAL",
    "NATIVE_SCHEDULE_COMBINED_CPML_CORE",
    "NATIVE_SCHEDULE_SOURCES",
    "NATIVE_SCHEDULE_MONITORS",
    "NATIVE_SCHEDULE_GRAPH_CACHE",
    "PROGRAM_LAYOUT_YEE_IN_PLACE",
    "PROGRAM_LAYOUT_YEE_TEMPORAL",
    "PROGRAM_LAYOUT_CPML_IN_PLACE",
    "PROGRAM_LAYOUT_SOURCE_IN_PLACE",
    "PROGRAM_LAYOUT_SOURCE_TEMPORAL_CPML",
    "PROGRAM_LAYOUT_MONITOR_IN_PLACE",
    "PROGRAM_LAYOUT_MONITOR_TEMPORAL_CPML",
    "FIELD_COUNT",
    "CPML_TERM_COUNT",
    "SOURCE_GROUP_COUNT",
    "SOURCE_GROUP_BUFFER_COUNT",
    "SOURCE_GROUP_COEFFICIENTS_INPUT",
    "SOURCE_GROUP_WAVEFORMS_INPUT",
    "SOURCE_GROUP_STARTS_INPUT",
    "MONITOR_INPUT_COUNT",
    "MONITOR_INDICES_INPUT",
    "MONITOR_WEIGHTS_INPUT",
    "MONITOR_FREQUENCIES_INPUT",
    "MONITOR_COMPONENT_MASKS_INPUT",
    "MONITOR_COUNTS_INPUT",
    "MONITOR_CODES_INPUT",
    "MONITOR_WINDOWS_INPUT",
    "MONITOR_DFT_RE_INPUT",
    "MONITOR_DFT_IM_INPUT",
    "MONITOR_DFT_WEIGHT_INPUT",
    "MONITOR_PHASE_SIN_INPUT",
    "MONITOR_PHASE_COS_INPUT",
    "MONITOR_PHASE_WINDOW_INPUT",
    "MONITOR_TIME_INPUT",
    "MONITOR_CURRENT_STEP_INPUT",
    "YEE_GRAPH_INPUT_COUNT",
    "YEE_GRAPH_OUTPUT_COUNT",
    "CPML_GRAPH_INPUT_COUNT",
    "CPML_GRAPH_OUTPUT_COUNT",
    "CPML_PHASE_INPUT_COUNT",
    "CPML_E_INPUT_OFFSET",
    "CPML_H_METRIC_OFFSET",
    "CPML_E_METRIC_OFFSET",
    "CPML_H_PSI_INPUT_OFFSET",
    "CPML_E_PSI_INPUT_OFFSET",
    "TEMPORAL_H_PSI_OUTPUT_OFFSET",
    "TEMPORAL_E_PSI_OUTPUT_OFFSET",
    "TEMPORAL_H_PSI_WORKSPACE_OFFSET",
    "TEMPORAL_E_PSI_WORKSPACE_OFFSET",
    "TEMPORAL_FIELD_WORKSPACE_INPUT",
    "TEMPORAL_PSI_WORKSPACE_INPUT",
]

CUDA_ABI_VERSION = 15
CUDA_COMPONENT_VERSION = "0.15.0"
CUDA_STREAMED_TARGET = "beamz_cuda_streamed"
CUDA_PROGRAM_TARGET = "beamz_cuda_program"
CUDA_HOPPER_TARGET = "beamz_cuda_hopper"

CUDA_STREAMED_TARGETS = frozenset(
    (
        CUDA_STREAMED_TARGET,
        CUDA_PROGRAM_TARGET,
    )
)

CUDA_GRAPH_CACHE = 1 << 7
CUDA_BF16_PSI = 1 << 12
CUDA_DEFAULT_FLAGS = CUDA_GRAPH_CACHE

NATIVE_SCHEDULE_CPML = 1 << 0
NATIVE_SCHEDULE_TEMPORAL = 1 << 1
NATIVE_SCHEDULE_UNIFORM_CPML = 1 << 2
NATIVE_SCHEDULE_PACKED_MATERIAL = 1 << 3
NATIVE_SCHEDULE_COMBINED_CPML_CORE = 1 << 4
NATIVE_SCHEDULE_SOURCES = 1 << 5
NATIVE_SCHEDULE_MONITORS = 1 << 6
NATIVE_SCHEDULE_GRAPH_CACHE = 1 << 7

PROGRAM_LAYOUT_YEE_IN_PLACE = 0
PROGRAM_LAYOUT_YEE_TEMPORAL = 1
PROGRAM_LAYOUT_CPML_IN_PLACE = 2
PROGRAM_LAYOUT_SOURCE_IN_PLACE = 3
PROGRAM_LAYOUT_SOURCE_TEMPORAL_CPML = 4
PROGRAM_LAYOUT_MONITOR_IN_PLACE = 5
PROGRAM_LAYOUT_MONITOR_TEMPORAL_CPML = 6

FIELD_COUNT = 6
CPML_TERM_COUNT = 6
SOURCE_GROUP_COUNT = 9
SOURCE_GROUP_BUFFER_COUNT = 3
SOURCE_GROUP_COEFFICIENTS_INPUT = 0
SOURCE_GROUP_WAVEFORMS_INPUT = 1
SOURCE_GROUP_STARTS_INPUT = 2
MONITOR_INPUT_COUNT = 15
MONITOR_INDICES_INPUT = 0
MONITOR_WEIGHTS_INPUT = 1
MONITOR_FREQUENCIES_INPUT = 2
MONITOR_COMPONENT_MASKS_INPUT = 3
MONITOR_COUNTS_INPUT = 4
MONITOR_CODES_INPUT = 5
MONITOR_WINDOWS_INPUT = 6
MONITOR_DFT_RE_INPUT = 7
MONITOR_DFT_IM_INPUT = 8
MONITOR_DFT_WEIGHT_INPUT = 9
MONITOR_PHASE_SIN_INPUT = 10
MONITOR_PHASE_COS_INPUT = 11
MONITOR_PHASE_WINDOW_INPUT = 12
MONITOR_TIME_INPUT = 13
MONITOR_CURRENT_STEP_INPUT = 14
YEE_GRAPH_INPUT_COUNT = 24
YEE_GRAPH_OUTPUT_COUNT = 6
CPML_GRAPH_INPUT_COUNT = 74
CPML_GRAPH_OUTPUT_COUNT = 18
CPML_PHASE_INPUT_COUNT = 31
CPML_E_INPUT_OFFSET = 37
CPML_H_METRIC_OFFSET = 68
CPML_E_METRIC_OFFSET = 71
CPML_H_PSI_INPUT_OFFSET = 31
CPML_E_PSI_INPUT_OFFSET = 62
TEMPORAL_H_PSI_OUTPUT_OFFSET = 12
TEMPORAL_E_PSI_OUTPUT_OFFSET = 18
TEMPORAL_H_PSI_WORKSPACE_OFFSET = 24
TEMPORAL_E_PSI_WORKSPACE_OFFSET = 30
TEMPORAL_FIELD_WORKSPACE_INPUT = 74
TEMPORAL_PSI_WORKSPACE_INPUT = 80
